version: "3.8"
services:
  chat-backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    env_file:
      - .env
  chat-ui-test:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"