version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - AUTH_ENABLED=False
      - LOGIN_PASSWORD=${LOGIN_PASSWORD}
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: